added hashed master passwording for security and better encryption

diff --git a/spasm b/spasm
--- a/spasm
+++ b/spasm
@@ -27,11 +27,13 @@
 
 #TODO reorganize whole file
 DATA="$HOME/.local/share/spasm" #TODO look into a way of improving this to fit more systems. XDG_DATA_HOME maybe?
-
+PREV_PID=
+MASTER_HASH=
 OPT_ADD=
 OPT_GET=
 PRINT_PASS=
 HAD_OPTS=
+PID=$(ps -p $$ -o ppid=)
 
 cat=""
 name=""
@@ -93,8 +95,7 @@ add_pass(){
 	mkdir -p "$DATA/$cat" && echo "adding password: $pass to $cat/$name" 
 
 	if [ -n "$(type "gpg2")" ]; then	
-		phrase="$cat/$name"
-		echo $pass | gpg2 -q --batch --passphrase $phrase -c > "$DATA/$cat/$name"
+		echo $pass | gpg2 -q --batch --passphrase "$MASTER_HASH" -c > "$DATA/$cat/$name"
 	else
 		echo $pass > "$DATA/$cat/$name"
 	fi
@@ -104,8 +105,7 @@ get_pass(){
 	[ ! -f "$DATA/$cat/$name" ] && echo "invalid argument -- no such category or password" && explode
 
 	if [ -n "$(type "gpg2")" ]; then
-		phrase="$cat/$name"
-		pass=$(gpg2 -q --batch --passphrase $phrase -d "$DATA/$cat/$name") 
+		pass=$(gpg2 -q --batch --passphrase "$MASTER_HASH" -d "$DATA/$cat/$name") 
 	else
 		pass=$(cat "$DATA/$cat/$name")
 	fi
@@ -133,28 +133,53 @@ delete_pass(){
 	[ ! "$(ls -A "$DATA/$cat")" ] && rmdir "$DATA/$cat"
 }
 
-optstring="hPTG:p:a:g:d:"
-while getopts $optstring FLAG; #TODO add handling for no options passed
-do	
-	HAD_OPTS=true
-	case "$FLAG" in	
-	h) usage && exit 0 ;;
-	G) [ -n "$pass" ] && explode || pass=$(gen_pass "$OPTARG") ;;#TODO add proper error messages
-	p) [ -n "$pass" ] && explode || pass=${OPTARG} ;;#TODO add proper error messages
-	a) parse_path "$OPTARG" && OPT_ADD=true ;;
-	g) parse_path "$OPTARG" && OPT_GET=true ;;
-	P) PRINT_PASS=true ;;
-	d) parse_path "$OPTARG" && delete_pass "$OPTARG" ;;
-	T) tree ;;
-	\?) usage; exit 1 ;;
-	esac
-done
+run(){
+	echo "$PID" > "$DATA/.pid"
+	optstring="hPTG:p:a:g:d:"
+	while getopts $optstring FLAG; #TODO add handling for no options passed
+	do	
+		HAD_OPTS=true
+		case "$FLAG" in	
+		h) usage && exit 0 ;;
+		G) [ -n "$pass" ] && explode || pass=$(gen_pass "$OPTARG") ;;#TODO add proper error messages
+		p) [ -n "$pass" ] && explode || pass=${OPTARG} ;;#TODO add proper error messages
+		a) parse_path "$OPTARG" && OPT_ADD=true ;;
+		g) parse_path "$OPTARG" && OPT_GET=true ;;
+		P) PRINT_PASS=true ;;
+		d) parse_path "$OPTARG" && delete_pass "$OPTARG" ;;
+		T) tree ;;
+		\?) usage; exit 1 ;;
+		esac
+	done
+	
+	if [ $HAD_OPTS ]; then
+		[ $OPT_ADD ] && add_pass
+		[ $OPT_GET ] && get_pass
+	else
+		echo "Error: spasm requires argument" && explode
+	fi
+}
 
-if [ $HAD_OPTS ]; then
-	[ $OPT_ADD ] && add_pass
-	[ $OPT_GET ] && get_pass
+#TODO find a better way to do newline after read
+[ -f "$DATA/.master" ] && MASTER_HASH=$(cat "$DATA/.master")
+if [ -n "$MASTER_HASH" ]; then	
+	[ -f "$DATA/.pid" ] && PREV_PID=$(cat "$DATA/.pid")
+	if [ -n "$PREV_PID" ] && [ "$PREV_PID" = "$PID" ]; then
+		run "$@"
+	else
+		read -s -p "enter master passphrase: " PASSPHRASE
+		echo "" 
+		if [ "$MASTER_HASH" == $(echo "$PASSPHRASE" | sha512sum | cut -d " " -f1) ]; then
+			run "$@"
+		else
+			echo "incorrect master passphrase" && exit 1
+		fi
+	fi
 else
-	echo "Error: spasm requires argument" && explode
+	read -s -p "no master passphrase found. please select one: " PASSPHRASE
+	echo ""
+	echo $(echo "$PASSPHRASE" | sha512sum | cut -d " " -f1) > "$DATA/.master" && echo "master passphrase added" && exit 0
 fi
+
 
 exit 0
